FROM python:3.12-slim

WORKDIR /app

COPY requirements-api.txt .

RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements-api.txt

COPY . .

EXPOSE 5075

ENV PYTHONUNBUFFERED=1

CMD ["python", "Movie_api.py"]