# Use an official Python runtime as the parent image
FROM python:3.12-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy only the requirements file first to leverage Docker cache
COPY requirements-gradio.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements-gradio.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 7860 available to the world outside this container
EXPOSE 7860

# Immediate logging without -t
ENV PYTHONUNBUFFERED=1

# Run Movie_gradio.py when the container launches
CMD ["python", "Movie_gradio.py"]