# Use an official Python runtime as the parent image
FROM python:3.12-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy only the requirements file first to leverage Docker cache
COPY requirements-api.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements-api.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5075 available to the world outside this container
EXPOSE 5075

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run MovieNet_api.py when the container launches
CMD ["python", "MovieNet_api.py", "--model_path", "saved_models/movie_poster_model.pth"]