FROM python:3.12-slim

WORKDIR /app

COPY requirements-gradio.txt .

RUN pip install --no-cache-dir -r requirements-gradio.txt

COPY Movie_gradio.py .
COPY requirements-gradio.txt .

EXPOSE 7860

ENV PYTHONUNBUFFERED=1

CMD ["python", "Movie_gradio.py"]